// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: manager.sql

package query

import (
	"context"
	"database/sql"
	"time"
)

const obtainTopLevelQueue = `-- name: ObtainTopLevelQueue :one
update quick_top_level_queue
set lease_id = $1
  , vesting_time = $2
where queue_zone = $3
    returning lease_id
`

type ObtainTopLevelQueueParams struct {
	LeaseID     sql.NullString
	VestingTime time.Time
	QueueZone   string
}

func (q *Queries) ObtainTopLevelQueue(ctx context.Context, arg ObtainTopLevelQueueParams) (sql.NullString, error) {
	row := q.db.QueryRow(ctx, obtainTopLevelQueue, arg.LeaseID, arg.VestingTime, arg.QueueZone)
	var lease_id sql.NullString
	err := row.Scan(&lease_id)
	return lease_id, err
}
