// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package query

import (
	"database/sql"
	"time"
)

type QuickTopLevelQueue struct {
	QueueZone   string
	VestingTime time.Time
	LeaseID     sql.NullString
	HashToken   int64
}

type QuickTopLevelQueuePointer struct {
	QueueZone   string
	VestingTime sql.NullTime
	HashToken   int64
}

type QuickWorkQueue struct {
	QueueZone   string
	ID          int64
	Payload     string
	Priority    sql.NullInt64
	VestingTime sql.NullTime
	LeaseID     sql.NullString
}
